# license_plates paths

# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: license_plates\train
val: license_plates\val  
test: license_plates\test  

# number of classes
nc: 1

# class names
names: [ 'license_plates' ]